Repository kurkle/chartjs-chart-sankey, pull requests merged in 2021-05, with the labels that each got.

#26 Fix overlap with unbalanced flows
  .editorconfig
  package-lock.json
  package.json
  src/layout.js
  test/fixtures/issue25.js
  test/fixtures/issue25.png
Labels: bug

#28 Add color mode other than gradient
  README.md
  src/flow.js
  test/fixtures/color-mode-from.js
  test/fixtures/color-mode-from.png
  test/fixtures/color-mode-gradient.js
  test/fixtures/color-mode-gradient.png
  test/fixtures/color-mode-to.js
  test/fixtures/color-mode-to.png
Labels: enhancement

#30 Fix chart.js URL in samples
  samples/utils.js
Labels: dependencies

#33 Fix maxY calculation when all nodes are at top
  src/layout.js
  test/fixtures/basic-y-0.js
  test/fixtures/basic-y-0.png
Labels: bug

#34 Multiline for labels
  src/controller.js
  test/fixtures/labels-multiline.js
  test/fixtures/labels-multiline.png
Labels: enhancement
